name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - phpunit-version: "8.5"
            composer-min-stability: stable
          - phpunit-version: "9.5"
            composer-min-stability: stable
          - phpunit-version: "10.0.x-dev"
            composer-min-stability: dev

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        coverage: none

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Update PHPUnit
      run:
        - composer config minimum-stability ${{ composer-min-stability }}
        - composer require --with-all-dependencies phpunit/phpunit:~${{ matrix.phpunit-version }}

    - name: Check PHPUnit version
      run: vendor/bin/phpunit --version

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: vendor/bin/phpunit
